# tuple is used to store multiple values which is structured, allows duplicated value and is immutable(unchangeable). It is denoted by ()
p_language = ('PHP','Python','Javascript','Python','Python')
print(p_language)
print(type(p_language))
print(len(p_language))
print(p_language.index('Javascript'))
print(p_language.count('Python'))
list_language = list(p_language)
print(type(list_language))
